### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by adynemo**
Hello Eirik!

As said in email, here is a PR to improve unit tests and increase coverage.
I also made a small improvement in the core with the addition of constant to handle types.

I hope you will like these changes ! 🙂

Ady.

### CODE REVIEW

**Comment by adynemo** [comment]
https://www.githubstatus.com/incidents/7p1nnvkgh96y

It will be necessary to restart the tests.

**Comment by eiriksm** [comment]
This looks amazing. Restarting the tests...

**Comment by eiriksm** [comment]
Great, thanks!

I assume that means this format works for you? 🤓

**Comment by adynemo** [comment]
> Great, thanks!
> 
> I assume that means this format works for you? nerd_face

Yes, it's perfect! Thanks for that. I will submit you a PR for the documentation about this part too, if you want 🙂

Edit: Oh and if you need more unit tests for the other parts of the violinist, not hesitate to request me.
Edit2: violinist-config must be updated to handle this new option, right?

**Comment by eiriksm** [comment]
Yes, violinist config must be updated first. So grateful if you are able to tackle that! ❤️

That package is also missing some test coverage if I remember correctly

**Pull request merged**
